### ISSUE TITLE
The getter 'name' was called on null.

### ISSUE THREAD

**Issue by BorisNaguet** [drails-dart/dson#23]
While having the #22 issue (and a few times before but because I was making another mistake) I had this error:

```
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
STACKTRACE: 
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      new IncorrectTypeTransform (package:dson/src/exceptions.dart:15:49)
#3      _convertValue (package:dson/src/deserializer.dart:235:17)
#4      _fillObject.<anonymous closure> (package:dson/src/deserializer.dart:147:22)
#5      List.forEach (dart:core-patch/array.dart:150)
#6      _fillObject (package:dson/src/deserializer.dart:134:23)
#7      _initiateClass (package:dson/src/deserializer.dart:346:10)
#8      _convertValue (package:dson/src/deserializer.dart:260:12)
#9      fromJson (package:dson/src/deserializer.dart:27:10)
```

It appears to come from:
```dart
  IncorrectTypeTransform(Object value, String type, [String key = "unknown"]) :
    _type = type,
    _field = key,
    _foundType = reflectType(value.runtimeType).name;
```

The problem appeared in the past when I forgot to call `_initMirrors();`
That was a hard one because the original Exception is hidden by this Exception in... Exception management.

However, I had it again when hitting #22 because type issues on native types are managed like that (on deserializer):
```dart
 else if (valueType == String) {
    if (value is String) {
      return value;
    } else {
      throw new IncorrectTypeTransform(value, 'String', key);
    }
  } else if (valueType == num) {
    if (value is num) {
      return value;
    } else {
      throw new IncorrectTypeTransform(value, 'num', key);
    }
  } else if (valueType == int) {
    if (value is int) {
      return value;
    } else {
      throw new IncorrectTypeTransform(value, 'int', key);
    }
  } else if (valueType == double) {
    if (value is double) {
      return value;
    } else {
      throw new IncorrectTypeTransform(value, 'double', key);
    }
  } else if (valueType == bool) {
    if (value is bool) {
      return value;
    } else {
      throw new IncorrectTypeTransform(value, 'bool', key);
    }
  } else if (valueType == 'list') {
    if (value is List) {
      return value;
    } else {
      throw new IncorrectTypeTransform(value, 'list', key);
    }
  } else if (valueType == Map) {
    if (value is Map) {
      return value;
    } else {
      throw new IncorrectTypeTransform(value, 'Map', key);
    }
```

but for me all these `IncorrectTypeTransform()` returns the same Exception because `reflectType(bool)` is null.
This is because base Dart types are not added to _classMirrors (and they don't need to, do they?)

**Comment by LexiBigCheese** [comment]
what was this object?

**Comment by BorisNaguet** [comment]
I don't have time to test it, but just map an `int` (say 10) in json to a `bool` field called `f` and you'll have this:
```dart
new IncorrectTypeTransform(10, 'bool', "f");
```
That should give you enough info to debug, but it's shadowed by the `NoSuchMethodError` exception in the constructor: `reflectType(10.runtimeType)` returns null.

That problem might seem avoidable, but it's frustrating when you must run in debug to understand your error, while it should just be printed in console.
