### ISSUE TITLE
Unable to serialize object to json

### ISSUE THREAD

**Issue by tezine** [drails-dart/dson#37]
Hi, 
I'm trying to serialize the object EVendor below into json, but I get an exception "the getter isEnum was called on null". Follow the object I'm trying to serialize below:

```
part 'package:ucount_flutter/entities/evendor.g.dart';

@serializable
class EVendor  extends _$EVendorSerializable{
  int id;
  int userID;
  int categoryID;
  String name;
  String description;
  DateTime dateInserted;

  EVendor({this.name, this.id});

  noSuchMethod(Invocation invocation) {
    super.noSuchMethod(invocation);
  }
}
```

```
Exception 

16:54:30.655 1 finer runtime.gc collection time 141ms • 43,4MB used of 59,5MB • isolates/766702422
16:54:47.908 2 finer runtime.gc collection time 160ms • 44,2MB used of 60,2MB • isolates/766702422
16:54:50.718 3 info flutter.tools I/flutter (12459): Salvou form:sdfdd
16:54:56.126 4 info flutter.tools E/flutter (12459): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
16:54:56.126 5 info flutter.tools E/flutter (12459): NoSuchMethodError: The getter 'isEnum' was called on null.
16:54:56.126 6 info flutter.tools E/flutter (12459): Receiver: null
16:54:56.126 7 info flutter.tools E/flutter (12459): Tried calling: isEnum
16:54:56.126 8 info flutter.tools E/flutter (12459): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
16:54:56.126 9 info flutter.tools E/flutter (12459): #1      _serializeObject (file:///C:/Users/tezine/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dson_core-0.15.0+1/lib/src/serializer.dart:114:18)
16:54:56.126 10 info flutter.tools E/flutter (12459): #2      objectToSerializable (file:///C:/Users/tezine/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dson_core-0.15.0+1/lib/src/serializer.dart:69:12)
16:54:56.126 11 info flutter.tools E/flutter (12459): #3      toJson (file:///C:/Users/tezine/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dson_core-0.15.0+1/lib/src/serializer.dart:27:28)
16:54:56.126 12 info flutter.tools E/flutter (12459): #4      _AppModel&Model&BaseModel&TransactionsModel&VendorsModel.insertVendor (package:ucount_flutter/models/vendors_model.dart:21:14)
16:54:56.126 13 info flutter.tools E/flutter (12459): <asynchronous suspension>
16:54:56.126 14 info flutter.tools E/flutter (12459): #5      VVendorsAddEditState._btnSaveClicked (package:ucount_flutter/views/vendors/vvendors_add_edit.dart:124:16)
16:54:56.126 15 info flutter.tools E/flutter (12459): #6      VVendorsAddEditState.build.<anonymous closure>.<anonymous closure> (package:ucount_flutter/views/vendors/vvendors_add_edit.dart:37:28)
16:54:56.126 16 info flutter.tools E/flutter (12459): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
16:54:56.126 17 info flutter.tools E/flutter (12459): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
16:54:56.126 18 info flutter.tools E/flutter (12459): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
16:54:56.126 19 info flutter.tools E/flutter (12459): #10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
16:54:56.126 20 info flutter.tools E/flutter (12459): #11     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
16:54:56.126 21 info flutter.tools E/flutter (12459): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
16:54:56.126 22 info flutter.tools E/flutter (12459): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
16:54:56.126 23 info flutter.tools E/flutter (12459): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
16:54:56.126 24 info flutter.tools E/flutter (12459): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
16:54:56.126 25 info flutter.tools E/flutter (12459): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
16:54:56.126 26 info flutter.tools E/flutter (12459): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
16:54:56.126 27 info flutter.tools E/flutter (12459): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
16:54:56.126 28 info flutter.tools E/flutter (12459): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
16:54:56.126 29 info flutter.tools E/flutter (12459): #20     _invoke1 (dart:ui/hooks.dart:134:13)
16:54:56.128 30 info flutter.tools E/flutter (12459): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
```

Here is my pubspec.yaml:
```
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^0.4.1
  intl: ^0.15.7
  sqflite: any
  scoped_model: ^0.3.0
  navigate: ^0.0.7
  dson: ^0.15.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  intl_translation: ^0.16.8
  build_runner: ^0.8.10
```

Any ideas? I'm running flutter 0.5.1 and dart 2.0.0 dev 58
Thank you, 
   Bruno.

**Comment by luisvt** [comment]
Let me check

**Comment by luisvt** [comment]
Did you initialize the reflector?

Could you show an example of the main.dart file

**Comment by tezine** [comment]
Hi, thank you for your help! 
Here's my main.dart: 
```
//region Imports
library example.object_to_json;
import 'package:flutter/material.dart';
import 'package:scoped_model/scoped_model.dart';
import 'package:ucount_flutter/localizations/localization.dart';
import 'package:ucount_flutter/models/AppModel.dart';
import 'package:ucount_flutter/redux_localization.dart';
import 'package:ucount_flutter/themes/theme_default.dart';
import 'package:ucount_flutter/views/vmenu.dart';
import 'package:dson/dson.dart';
part 'main.g.dart'; //precis para dson
//endregion

void main() {
  _initMirrors(); //precisa disso para dson funcionar
  runApp(new UCountApp());
}

class UCountApp extends StatelessWidget {

  UCountApp();

  @override
  Widget build(BuildContext context) {
    return ScopedModel<AppModel>(
      model: new AppModel(),
      child: new MaterialApp(
        home: VMenu(title:'UCount'),//nao precisa qdo usa Navigator
        title: new ReduxLocalizations().appTitle,
        theme: ThemeDefault.theme,
        localizationsDelegates: [
          new ArchSampleLocalizationsDelegate(),
          new ReduxLocalizationsDelegate(),
        ],
//        routes: UCountRoutes.getRoutes()//usado com Navigator
      ),
    );
  }
}

```

**Comment by LexiBigCheese** [comment]
have you used the build script yet?
You should probably do that if you haven't.

**Comment by tezine** [comment]
Yes, I had executed "flutter packages pub run build_runner build". What am I missing ?

**Comment by luisvt** [comment]
Thanks I'll try do reproduce it at afternoon

**Comment by LexiBigCheese** [comment]
hey what *are* you serializing / reflecting? because i don't see anything that could contain something to serialize / reflect. and if there's nothing to serialize/reflect there won't be any main.g.dart, will there?

**Comment by tezine** [comment]
I had to add the line `library example.object_to_json;` into EVendor.dart and 
I had to add `import 'package:ucount_flutter/entities/evendor.dart'; ` into main.dart. Now it's serializing to json and map. 

Now the new problem is that is not deserializing back from a map. 
I have the following code to deserialize from sqlite:
```
void reloadVendors()async{
    vendorList.clear();
    List<Map> records=await database.query(Defines.tableVendors);
    records.forEach((record){
      vendorList.add( fromMap(record,EVendor));
    });
  }
```

I get the exception below when it's executed: 
```
16:18:37.523 45 info flutter.tools E/flutter (19687): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
16:18:37.523 46 info flutter.tools E/flutter (19687): No constructor found: Class [EVendor] doesn't either have a constructor without arguments or arguments matching final fields.
16:18:37.523 47 info flutter.tools E/flutter (19687): #0      _initiateClass (file:///C:/Users/tezine/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dson_core-0.15.0+1/lib/src/deserializer.dart:213:7)
16:18:37.523 48 info flutter.tools E/flutter (19687): #1      _convertValue (file:///C:/Users/tezine/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dson_core-0.15.0+1/lib/src/deserializer.dart:151:12)
16:18:37.523 49 info flutter.tools E/flutter (19687): #2      fromMap (file:///C:/Users/tezine/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dson_core-0.15.0+1/lib/src/deserializer.dart:48:10)
16:18:37.523 50 info flutter.tools E/flutter (19687): #3      _AppModel&Model&BaseModel&TransactionsModel&VendorsModel.reloadVendors.<anonymous closure> (package:ucount_flutter/models/vendors_model.dart:18:23)
16:18:37.523 51 info flutter.tools E/flutter (19687): #4      _ListBase&Object&ListMixin.forEach (dart:collection/list.dart:68:13)
16:18:37.523 52 info flutter.tools E/flutter (19687): #5      _AppModel&Model&BaseModel&TransactionsModel&VendorsModel.reloadVendors (package:ucount_flutter/models/vendors_model.dart:17:13)
```

**Comment by luisvt** [comment]
ok, so the error basically is caused because there is no a default constructor without parameters it could take.

My recomendation would be that you create a separate constructor for `id` and `name`, or you could make them final.

```dart
@serializable
class EVendor extends _$EVendorSerializable {
  int id;
  int userID;
  int categoryID;
  String name;
  String description;
  DateTime dateInserted;

  EVendor();

  EVendor.from({this.name, this.id});

  noSuchMethod(Invocation invocation) {
    super.noSuchMethod(invocation);
  }
}
```

**Comment by luisvt** [comment]
In fact, I think that's a bug so let me fix it

**Comment by tezine** [comment]
Hi Luis, thank you very much for your help! It worked!
It would be great to add constructors with parameters.

**Comment by luisvt** [comment]
please upgrade to latest version and check if now it works with default parameters without adding the extra constructor

**Comment by tezine** [comment]
Excelent! It worked Luis! Thank you!!
