### ISSUE TITLE
Enums not serialized to json/map

### ISSUE THREAD

**Issue by tezine** [drails-dart/dson#39]
Hi, 
I'm sorry to bother again, but it seems enums are not being serialized. 
TransactionType in the class below throws an exception when serializing to map:
```
library example.object_to_json; // required by dson
import 'package:dson/dson.dart';
import 'package:ucount_flutter/codes/cdefines.dart';
part 'package:ucount_flutter/entities/etransaction.g.dart';//required by dson

@serializable
class ETransaction extends _$ETransactionSerializable{
  int id;
  TransactionType transactionType;
  int userID;
  String title;
  String description;
  double total;
  int categoryID;
  int vendorID;
  DateTime dt;
  DateTime dateInserted;

  ETransaction({this.userID,this.title,this.total,this.dt, this.transactionType, this.id});

  noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}
```

Here is the TransactionType enum:
```
enum TransactionType { 
  expense,
  income,
}
```

Follow the exception below:
```
14:42:59.439 4 info flutter.tools E/flutter ( 9976): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
14:42:59.439 5 info flutter.tools E/flutter ( 9976): NoSuchMethodError: The getter 'isEnum' was called on null.
14:42:59.439 6 info flutter.tools E/flutter ( 9976): Receiver: null
14:42:59.439 7 info flutter.tools E/flutter ( 9976): Tried calling: isEnum
14:42:59.439 8 info flutter.tools E/flutter ( 9976): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
14:42:59.439 9 info flutter.tools E/flutter ( 9976): #1      _serializeObject (file:///C:/Users/tezine/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dson_core-0.15.1/lib/src/serializer.dart:114:18)
14:42:59.439 10 info flutter.tools E/flutter ( 9976): #2      objectToSerializable (file:///C:/Users/tezine/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dson_core-0.15.1/lib/src/serializer.dart:69:12)
14:42:59.439 11 info flutter.tools E/flutter ( 9976): #3      _pushField (file:///C:/Users/tezine/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dson_core-0.15.1/lib/src/serializer.dart:180:25)
14:42:59.439 12 info flutter.tools E/flutter ( 9976): #4      _serializeObject.<anonymous closure> (file:///C:/Users/tezine/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dson_core-0.15.1/lib/src/serializer.dart:127:40)
14:42:59.439 13 info flutter.tools E/flutter ( 9976): #5      _ImmutableMap.forEach (dart:core/runtime/libimmutable_map.dart:45:8)
14:42:59.439 14 info flutter.tools E/flutter ( 9976): #6      _serializeObject (file:///C:/Users/tezine/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dson_core-0.15.1/lib/src/serializer.dart:126:23)
```

**Comment by luisvt** [comment]
you need to annotate it with `@serializable`

```dart
@serializable
enum TransactionType { 
  expense,
  income,
}
```

**Comment by tezine** [comment]
Thanks Luis, it worked. I had to modify the file (cdefines.dart) into this:
```
library example.object_to_json; // required by dson
import 'package:dson/dson.dart';
part 'package:ucount_flutter/codes/cdefines.g.dart';//required by dson

@serializable
enum TransactionType {
  expense,
  income,
}
```
