### ISSUE TITLE
Calling toMap() on an object with null fields throws an error

### ISSUE THREAD

**Issue by lynzrand** [drails-dart/dson#46]
**`dson` version: 0.15.5**

**`dson_core` version: 0.15.4**

Minimal example to reproduce bug:

```dart
/* test.dart */
import 'package:dson/dson.dart';

part 'test.g.dart';

main(List<String> args) {
  toMap(new SimpleTest());
}

@serializable
class SimpleTest {
  String x;
  SimpleTest() {
    x = null;
  }
}
```

After `build_runner build`, run the script and the following error was thrown:

```
Unhandled exception:
NoSuchMethodError: The getter 'isEnum' was called on null.
Receiver: null
Tried calling: isEnum
#0      Object.noSuchMethod (dart:core/runtime/lib/object_patch.dart:50:5)
#1      _serializeObject (file:/// [...] /AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dson_core-0.15.4/lib/src/serializer.dart:113:18)
#2      objectToSerializable (file:/// [...] /AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dson_core-0.15.4/lib/src/serializer.dart:69:12)
#3      toMap (file:// [...] /AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dson_core-0.15.4/lib/src/serializer.dart:42:5)
#4      main ( [...] test.dart:16:3)
#5      _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:298:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

The error appears to be from [this line in `dson_core`](https://github.com/dart-league/dson_core/blob/e6701e5ca2bc31d05abf05254356cdd3df059233/lib/src/serializer.dart#L113), so I went to see the code. It seems that this instance variable somehow passed the primitive type check at line 11 (which in theory *should* block this null value):

```dart
bool isPrimitive(value) => value is String || value is num || value is bool || value == null;
```

Then this null value got to `_serializeObject()` function, passed to the [`reflect()` function in `built_mirrors_core`](https://github.com/dart-league/built_mirrors_core/blob/f4c639236eba7a467271d0da4d9146f452450c86/lib/built_mirrors.dart#L23) and returned as null instead of a `ClassMirror` object.

I have little idea how this should be fixed though...

---
update: fixed format error

**Comment by luisvt** [comment]
your error is because you didn't call `_initMirrors()` function in your `main`:

your full code should look as fallow: 

```dart
library test; // don't forget to change the name of your library

import 'package:dson/dson.dart';

part 'test.g.dart';

main(List<String> args) {
  _initMirrors(); // This call is needed to initialize mirrors before doing serialization/deserialization

  toMap(new SimpleTest());
}

@serializable
class SimpleTest {
  String x;
  SimpleTest() {
    x = null;
  }
}```

**Comment by lynzrand** [comment]
Oh, my fault. Thanks, and sorry for taking your time!

Rynco Maekawa
--

________________________________

**Comment by luisvt** [comment]
don't worry, it's cool to help users of my library

**Comment by lynzrand** [comment]
Sorry, but the problem is here again. I have called `_initMirrors()` in the main isolate, but now I'm working in another isolate where no entry point like main function. Where should I call `_initMirrors` in this situation?

More precisely, I'm working with the `Aqueduct` HTTP server package and I need to serialize stuff. The serializer/deserializer coming with the package has not enough features for me to fiddle with (like ignoring fields at runtime). Aqueduct works by using separate isolates to handle HTTP requests, and in one of those Isolates I still got this "not initialized" error.

![图片](https://user-images.githubusercontent.com/10259119/55076617-e06a6700-50d0-11e9-8bb3-f0c4c960c4ff.png)

What should I do now?

**Comment by luisvt** [comment]
could you show me your full code or a full example?

**Comment by 01010101lzy** [comment]
Sure.

My full code is in this repository: https://github.com/01010101lzy/akali/

The issue occurs around this piece of code<https://github.com/01010101lzy/akali/blob/375079783a8168ad2cfc79505f334de3670b6b9f/lib/data/db/mongodb.dart#L145>

(the “Pic.asMap()” method calls “toMap(this)”)

Which is called by this function<https://github.com/01010101lzy/akali/blob/375079783a8168ad2cfc79505f334de3670b6b9f/lib/api/imgRequest.dart#L213>

Thanks for your help!

发件人: Luis Vargas<mailto:notifications@github.com>
发送时间: 2019年3月28日 6:25
收件人: dart-league/dson<mailto:dson@noreply.github.com>
抄送: Rynco Li<mailto:plok314159265@163.com>; Author<mailto:author@noreply.github.com>
主题: Re: [dart-league/dson] Calling toMap() on an object with null fields throws an error (#46)


could you show me your full code or a full example?

―

**Comment by lynzrand** [comment]
The issue occurs here:
<https://github.com/01010101lzy/akali/blob/375079783a8168ad2cfc79505f334de3670b6b9f/lib/data/db/mongodb.dart#L145>

```dart
  Future<ActionResult<Pic>> updateImgInfo(Pic newInfo, String id) async {
    var _id = ObjectId.fromHexString(id);
    var result = await picCollection.update(where.id(_id), newInfo.asMap());
    newInfo.id = _id;
    bool success = result['nModified'] > 0;
    if (success)
      return ActionResult()
        ..success = true
        ..data = newInfo
        ..affected = result['nModified'];
    else
      return ActionResult()..success = false;
}
```

In this function, the `Pic.asMap()` method is calling `return toMap(this)` inside.

This function is called by this line:
<https://github.com/01010101lzy/akali/blob/375079783a8168ad2cfc79505f334de3670b6b9f/lib/api/imgRequest.dart#L213>

This is the handling function of HTTP PUT of `/api/v1/img/:id` path

```dart
  /// PUT `img/:id`
  ///
  /// Updates image [id]'s data by [newInfo].
  /// Requires authorization beforehand.
  @Operation.put('id')
  Future<Response> putImage(
    @Bind.path('id') String id,
    @Bind.body() Pic newInfo, [
    @Bind.query('access_token') String tokenQuery,
    @Bind.header('Access-Token') String tokenHeader,
  ]) async {
    var result;
    try {
      result = await db.updateImgInfo(newInfo, id);
    } catch (e, stack) {
      logger.severe("Error in putImage()", e, stack);
      throw Response.serverError(
          body: {'error': e, 'message': result, 'stackTrace': stack});
    }
    return Response.ok(result);
  }
```

The rest of the handling process is managed by Aqueduct so I don't have access on them.

The whole repository is here: <https://github.com/01010101lzy/akali>
